definitions:
  handler.Error:
    properties:
      code:
        type: integer
      error:
        type: string
      errors:
        items:
          type: string
        type: array
      input_errors:
        additionalProperties:
          type: string
        type: object
    type: object
  request.ConfirmEmail:
    properties:
      code:
        type: string
    type: object
  request.UserSignIn:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  request.UserSignUp:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  response.Status:
    properties:
      success:
        type: boolean
    type: object
  response.UserSignIn:
    properties:
      id:
        type: integer
      token:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /users/confirm-email/:
    post:
      operationId: UserSignOut
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Status'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      security:
      - ApiKeyAuth: []
      summary: Logout
      tags:
      - users
  /users/sign-in/:
    post:
      consumes:
      - application/json
      operationId: UserSignIn
      parameters:
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.UserSignIn'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.UserSignIn'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      security:
      - ApiKeyAuth: []
      summary: User auth
      tags:
      - users
  /users/sign-up/:
    post:
      consumes:
      - application/json
      operationId: UserSignUp
      parameters:
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.UserSignUp'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Status'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      security:
      - ApiKeyAuth: []
      summary: User registration
      tags:
      - users
swagger: "2.0"
