definitions:
  ds.Book:
    properties:
      author_link:
        type: string
      author_name:
        type: string
      cover_file_id:
        type: string
      created_at:
        type: string
      description:
        type: string
      homepage:
        type: string
      id:
        type: string
      owner_id:
        type: string
      preview_file_id:
        type: string
      public_id:
        type: string
      published_at:
        type: string
      release_date:
        type: string
      status:
        $ref: '#/definitions/ds.EntityStatus'
      title:
        type: string
      updated_at:
        type: string
      visibility:
        $ref: '#/definitions/ds.EntityVisibility'
    type: object
  ds.EntityStatus:
    enum:
    - review
    - approved
    - rejected
    type: string
    x-enum-varnames:
    - EntityStatusUnderReview
    - EntityStatusApproved
    - EntityStatusRejected
  ds.EntityVisibility:
    enum:
    - public
    - private
    - unlisted
    type: string
    x-enum-varnames:
    - EntityVisibilityPublic
    - EntityVisibilityPrivate
    - EntityVisibilityUnlisted
  ds.File:
    properties:
      created_at:
        type: string
      id:
        type: string
      mime_type:
        type: string
      name:
        type: string
      owner_id:
        type: string
      purpose:
        $ref: '#/definitions/ds.FilePurpose'
      size:
        type: integer
      type:
        $ref: '#/definitions/file.Type'
    type: object
  ds.FilePurpose:
    enum:
    - book-cover
    type: string
    x-enum-varnames:
    - FilePurposeBookCover
  file.Type:
    enum:
    - other
    - image
    - video
    type: string
    x-enum-varnames:
    - TypeOther
    - TypeImage
    - TypeVideo
  handler.Error:
    properties:
      code:
        type: integer
      error:
        type: string
      errors:
        items:
          type: string
        type: array
      input_errors:
        additionalProperties:
          type: string
        type: object
    type: object
  request.ChangePassword:
    properties:
      new_password:
        type: string
      old_password:
        type: string
    type: object
  request.ChangeUsername:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  request.ConfirmEmail:
    properties:
      code:
        type: string
    type: object
  request.CreateBook:
    properties:
      author_link:
        type: string
      author_name:
        type: string
      cover_file_id:
        type: string
      description:
        type: string
      homepage:
        type: string
      release_date:
        type: string
      title:
        type: string
      visibility:
        $ref: '#/definitions/ds.EntityVisibility'
    type: object
  request.DeleteUser:
    properties:
      password:
        type: string
    type: object
  request.EmailChangeRequest:
    properties:
      email:
        type: string
    type: object
  request.PasswordReset:
    properties:
      password:
        type: string
      token:
        type: string
    type: object
  request.PasswordResetRequest:
    properties:
      email:
        type: string
    type: object
  request.UserSignIn:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  request.UserSignUp:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  response.FilterBooks:
    properties:
      count:
        type: integer
      data:
        items:
          $ref: '#/definitions/ds.Book'
        type: array
    type: object
  response.Status:
    properties:
      success:
        type: boolean
    type: object
  response.UserSignIn:
    properties:
      id:
        type: string
      token:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /books/:
    get:
      consumes:
      - application/json
      operationId: FilterBooks
      parameters:
      - in: query
        name: page
        type: integer
      - in: query
        name: per_page
        type: integer
      - in: query
        name: search
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.FilterBooks'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      security:
      - ApiKeyAuth: []
      summary: Filter books
      tags:
      - books
    post:
      consumes:
      - application/json
      operationId: CreateBook
      parameters:
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.CreateBook'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/ds.Book'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      security:
      - ApiKeyAuth: []
      summary: Create a new book
      tags:
      - books
  /books/{id}/:
    get:
      consumes:
      - application/json
      operationId: GetBook
      parameters:
      - description: Book ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/ds.Book'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      security:
      - ApiKeyAuth: []
      summary: Get book
      tags:
      - books
  /files/:
    post:
      consumes:
      - multipart/form-data
      operationId: UploadFile
      parameters:
      - description: File
        in: body
        name: file
        required: true
        schema:
          items:
            type: integer
          type: array
      - description: File purpose
        in: body
        name: purpose
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.Status'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      security:
      - ApiKeyAuth: []
      summary: Upload file
      tags:
      - files
  /files/{id}/:
    delete:
      consumes:
      - application/json
      operationId: DeleteFile
      parameters:
      - description: File ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Status'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      security:
      - ApiKeyAuth: []
      summary: Delete file
      tags:
      - files
    post:
      consumes:
      - application/json
      operationId: GetFileMetadata
      parameters:
      - description: File ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ds.File'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      security:
      - ApiKeyAuth: []
      summary: Get file metadata
      tags:
      - files
  /users/:
    delete:
      consumes:
      - application/json
      operationId: DeleteUser
      parameters:
      - description: Password
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.DeleteUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Status'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.Error'
        "422":
          description: Validation error or incorrect password
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      security:
      - ApiKeyAuth: []
      summary: Delete user account
      tags:
      - users
  /users/confirm-email/:
    post:
      consumes:
      - application/json
      operationId: ConfirmEmail
      parameters:
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.ConfirmEmail'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Status'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      security:
      - ApiKeyAuth: []
      summary: Confirm email
      tags:
      - users
  /users/email/:
    post:
      consumes:
      - application/json
      operationId: EmailChangeConfirm
      parameters:
      - description: Old and new passwords
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.EmailChangeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Status'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.Error'
        "422":
          description: Validation error
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      security:
      - ApiKeyAuth: []
      summary: Confirm changing user email
      tags:
      - users
  /users/password-reset-request/:
    post:
      consumes:
      - application/json
      operationId: PasswordResetRequest
      parameters:
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.PasswordResetRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Status'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      security:
      - ApiKeyAuth: []
      summary: Initiate password reset
      tags:
      - users
  /users/password-reset/:
    post:
      consumes:
      - application/json
      operationId: PasswordResetConfirm
      parameters:
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.PasswordReset'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Status'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      security:
      - ApiKeyAuth: []
      summary: Password reset
      tags:
      - users
  /users/password/:
    post:
      consumes:
      - application/json
      operationId: ChangePassword
      parameters:
      - description: Old and new passwords
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.ChangePassword'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Status'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.Error'
        "422":
          description: Validation error or incorrect old password
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      security:
      - ApiKeyAuth: []
      summary: Change user password
      tags:
      - users
  /users/sign-in/:
    post:
      consumes:
      - application/json
      operationId: UserSignIn
      parameters:
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.UserSignIn'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.UserSignIn'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      security:
      - ApiKeyAuth: []
      summary: User auth
      tags:
      - users
  /users/sign-out/:
    post:
      operationId: UserSignOut
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Status'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      security:
      - ApiKeyAuth: []
      summary: Logout
      tags:
      - users
  /users/sign-up/:
    post:
      consumes:
      - application/json
      operationId: UserSignUp
      parameters:
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.UserSignUp'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Status'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      security:
      - ApiKeyAuth: []
      summary: User registration
      tags:
      - users
  /users/username/:
    post:
      consumes:
      - application/json
      operationId: ChangeUsername
      parameters:
      - description: New username and password
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.ChangeUsername'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Status'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.Error'
        "422":
          description: Validation error or incorrect password
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      security:
      - ApiKeyAuth: []
      summary: Change username
      tags:
      - users
swagger: "2.0"
